import { NgModule } from '@angular/core';
import { ColorPickerModule } from 'ngx-color-picker';

import {
  // MatAutocompleteModule,
  // MatButtonModule,
  // MatButtonToggleModule,
  // MatCardModule,
  MatCheckboxModule,
  // MatChipsModule,
  // MatDatepickerModule,
  // MatDialogModule,
  // MatExpansionModule,
  // MatGridListModule,
  // MatIconModule,
  // MatInputModule,
  // MatListModule,
  // MatMenuModule,
  // MatNativeDateModule,
  // MatProgressBarModule,
  // MatProgressSpinnerModule,
  // MatRadioModule,
  // MatRippleModule,
  // MatSelectModule,
  // MatSidenavModule,
  MatSliderModule, // The module require hammerjs to getting smoothly
  // MatSlideToggleModule,
  // MatSnackBarModule,
  // MatStepperModule,
  MatTableModule,
  MatSortModule,
  MatFormFieldModule,
  // MatTabsModule,
  // MatToolbarModule,
  MatTooltipModule,
} from '@angular/material';


@NgModule({
  imports: [
    // Material
    // MatAutocompleteModule,
    // MatButtonModule,
    // MatButtonToggleModule,
    // MatCardModule,
    MatCheckboxModule,
    // MatChipsModule,
    // MatDatepickerModule,
    // MatDialogModule,
    // MatExpansionModule,
    // MatGridListModule,
    // MatIconModule,
    // MatInputModule,
    // MatListModule,
    // MatMenuModule,
    // MatProgressBarModule,
    // MatProgressSpinnerModule,
    // MatRadioModule,
    // MatRippleModule,
    // MatSelectModule,
    // MatSidenavModule,
    // MatSlideToggleModule,
    MatSliderModule,
    // MatSnackBarModule,
    // MatStepperModule,
    MatTableModule,
    MatSortModule,
    MatFormFieldModule,
    // MatTabsModule,
    // MatToolbarModule,
    MatTooltipModule,
    // MatNativeDateModule,
    ColorPickerModule
  ],
  exports: [
    // Material
    // MatAutocompleteModule,
    // MatButtonModule,
    // MatButtonToggleModule,
    // MatCardModule,
    MatCheckboxModule,
    // MatChipsModule,
    // MatDatepickerModule,
    // MatDialogModule,
    // MatExpansionModule,
    // MatGridListModule,
    // MatIconModule,
    // MatInputModule,
    // MatListModule,
    // MatMenuModule,
    // MatProgressBarModule,
    // MatProgressSpinnerModule,
    // MatRadioModule,
    // MatRippleModule,
    // MatSelectModule,
    // MatSidenavModule,
    // MatSlideToggleModule,
    MatSliderModule,
    // MatSnackBarModule,
    // MatStepperModule,
    MatTableModule,
    MatSortModule,
    MatFormFieldModule,
    // MatTabsModule,
    // MatToolbarModule,
    MatTooltipModule,
    // MatNativeDateModule,
    ColorPickerModule
  ]
})


export class MaterialModule{}
